### ISSUE TITLE
DateFormat

### ISSUE THREAD

**Issue by McFSR** [Amberg/DocxTemplater#12]
Hi
I like your library very much and would like to use it in my application.
I found an issue with date formatting:
According to the docs, this should work: {{MyCollection.MyDate}:F("MM/dd/yyyy")}. But this just resolves to the string "MM/dd/yyy".
By trial and error I found out this works: {{MyCollection.MyDate}:ToString("MM/dd/yyyy")}
So I use "ToString" instead of "Format". Is this a bug?

**Comment by Amberg** [comment]
The documentation was incorrect.
Use `'` isnstead of `"`
`{{MyCollection.MyDate}:F('MM/dd/yyyy')}`
should work
I am pleased that my library is useful to you. If you like, please give it a star.

**Comment by McFSR** [comment]
Thank you very much!
It is indeed very usefull - and free :-)
